-- Phase 6: 애드센스 광고 슬롯, 변경 감사 로그 및 비개인식별 분석 로그 테이블 스키마 생성

CREATE TABLE IF NOT EXISTS ad_placements (
  id VARCHAR(255) PRIMARY KEY,
  slot_key VARCHAR(255) UNIQUE NOT NULL,
  page_type VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,
  device_target VARCHAR(50) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  min_content_length INTEGER NOT NULL DEFAULT 0,
  ad_format VARCHAR(100) NOT NULL,
  reserve_height INTEGER NOT NULL DEFAULT 0,
  consent_required BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ad_audit_logs (
  id VARCHAR(255) PRIMARY KEY,
  placement_id VARCHAR(255) NOT NULL,
  slot_key VARCHAR(255) NOT NULL,
  action VARCHAR(100) NOT NULL,
  changed_by VARCHAR(255) NOT NULL,
  changes TEXT NOT NULL, -- JSON string
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS analytics_logs (
  id VARCHAR(255) PRIMARY KEY,
  event_name VARCHAR(100) NOT NULL,
  page_type VARCHAR(100) NOT NULL,
  session_id VARCHAR(255) NOT NULL,
  properties TEXT NOT NULL, -- JSON string
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
